name: Deploy Road Inspection

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H YOUR_SERVER_IP >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh -i ~/.ssh/id_ed25519 admin123@YOUR_SERVER_IP << 'EOF'
            cd ~/road_inspection
            git reset --hard
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart road_inspection.service
          EOF
